Move declaration of visibility attributes before definition.
When compiling with clang, the visibility attributes are ignored
since they are after the definition of the exported function.

Fix this by moving the attribute declaration before the function.

attr.c:439:1: error: attribute declaration must precede definition [-Werror,-Wignored-attributes]
EXPORT_SYMBOL(mnl_attr_put_u8);
^
./internal.h:7:41: note: expanded from macro 'EXPORT_SYMBOL'
                                              ^
./internal.h:6:35: note: expanded from macro '__visible'
                                               ^
attr.c:435:6: note: previous definition is here
void mnl_attr_put_u8(struct nlmsghdr *nlh, uint16_t type, uint8_t data)
     ^

Signed-off-by: Peter Foley <pefoley2@pefoley.com>